### PR TITLE
Insert an optional field for idnumber (studentid) to SAML auth method

### PR DESCRIPTION
**Pull request by nmoller**
We need it for our work and we thought that could be interesting to everybody.
We have just included it into the branch 16.10_STABLE (because it is the one we are working on) but we can add the changes in master if it could help the integrator.

### CODE REVIEW

**Comment by nmoller** [comment]
If you think it could be interesting. **We'll implement the strings needed to make it proper.**

**Comment by anitsirk** [comment]
Hi. I created https://bugs.launchpad.net/mahara/+bug/1640893 for it and we'll pull the patch into our review system at https://reviews.mahara.org

**Comment by nmoller** [comment]
The lang string was added to the patch.

**Comment by anitsirk** [comment]
This functionality was released with Mahara 17.04. Please see https://bugs.launchpad.net/mahara/+bug/1640893 for more information.

**Pull request closed without merging**
